# Generated by Django 3.1.6 on 2021-02-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craiglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'searches'},
        ),
    ]
